FROM erza/restaurantscraper:1.0.0

WORKDIR /usr/src/app
COPY ../ .
RUN apk update && apk add git
#RUN git clone https://erzascarlet06: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@github.com/erzascarlet06/restaurant_web.git /usr/src/app
